platform :ios, '11.0'
use_frameworks!

target 'Geofirestore_Example' do
  pod 'Geofirestore', :path => '../'

  target 'Geofirestore_Tests' do
    inherit! :search_paths

    
    pod 'Quick'
    pod 'Nimble'
  end
end
