use_frameworks!

target 'Geofirestore_Example' do
  pod 'Geofirestore', :path => '../'

  target 'Geofirestore_Tests' do
    inherit! :search_paths

    
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
